/*
 * generated by Xtext 2.9.0.beta5
 */
package hu.bme.thesis.dsl.rules.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor class RuleDslUiModule extends AbstractRuleDslUiModule {
}
