/*
 * generated by Xtext 2.9.0.beta5
 */
package org.eclipse.viatra.cep.mqtt.midl.ui.contentassist

import org.eclipse.viatra.cep.mqtt.midl.ui.contentassist.AbstractMIDLProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MIDLProposalProvider extends AbstractMIDLProposalProvider {
}
