/*
 * generated by Xtext 2.9.0.beta5
 */
package hu.bme.thesis.dsl.rules


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RuleDslStandaloneSetup extends RuleDslStandaloneSetupGenerated {

	def static void doSetup() {
		new RuleDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}

}
