/*
 * generated by Xtext 2.9.0.beta5
 */
package hu.bme.thesis.dsl.rules


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RuleDslRuntimeModule extends AbstractRuleDslRuntimeModule {
}
