/*
 * generated by Xtext 2.9.0.beta5
 */
package hu.bme.thesis.dsl.sensors.ui.contentassist

import hu.bme.thesis.dsl.sensors.ui.contentassist.AbstractSensorsDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SensorsDslProposalProvider extends AbstractSensorsDslProposalProvider {
}
