/*
 * generated by Xtext 2.9.0.beta5
 */
package hu.bme.thesis.dsl.sensors


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SensorsDslStandaloneSetup extends SensorsDslStandaloneSetupGenerated {

	def static void doSetup() {
		new SensorsDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}

}
