/*
 * generated by Xtext 2.9.0.beta5
 */
package hu.bme.thesis.dsl.sensors


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SensorsDslRuntimeModule extends AbstractSensorsDslRuntimeModule {
}
