/*
 * generated by Xtext 2.9.0.beta5
 */
package hu.bme.thesis.dsl.ui.contentassist

import hu.bme.thesis.dsl.ui.contentassist.AbstractSensorDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SensorDslProposalProvider extends AbstractSensorDslProposalProvider {
}
