/*
 * generated by Xtext 2.9.0.beta5
 */
package hu.bme.thesis.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SensorDslStandaloneSetup extends SensorDslStandaloneSetupGenerated {

	def static void doSetup() {
		new SensorDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}

}
