/*
 * generated by Xtext 2.9.0.beta5
 */
package org.eclipse.viatra.cep.mqtt.midl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MIDLRuntimeModule extends AbstractMIDLRuntimeModule {
}
