/*
 * generated by Xtext 2.9.0.beta5
 */
package org.eclipse.viatra.cep.mqtt.midl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MIDLStandaloneSetup extends MIDLStandaloneSetupGenerated {

	def static void doSetup() {
		new MIDLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}

}
